// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26uD33oSqF-Do-r4YPF1O5NnnUObH0rc',
    appId: '1:468315049178:web:2d60cde5d9a5c280ac69e3',
    messagingSenderId: '468315049178',
    projectId: 'anima-master-toolkit-fork',
    authDomain: 'anima-master-toolkit-fork.firebaseapp.com',
    storageBucket: 'anima-master-toolkit-fork.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUeINTfrmiCoKE4SrzoFBSN7JJ5oNBznw',
    appId: '1:468315049178:android:7982f2559df54963ac69e3',
    messagingSenderId: '468315049178',
    projectId: 'anima-master-toolkit-fork',
    storageBucket: 'anima-master-toolkit-fork.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB26uD33oSqF-Do-r4YPF1O5NnnUObH0rc',
    appId: '1:468315049178:web:da42338a64580a79ac69e3',
    messagingSenderId: '468315049178',
    projectId: 'anima-master-toolkit-fork',
    authDomain: 'anima-master-toolkit-fork.firebaseapp.com',
    storageBucket: 'anima-master-toolkit-fork.firebasestorage.app',
  );
}
