/// Tablas del Core Exxet que el parser de PNJ necesita para completar lo que
/// los perfiles dan solo por nombre.
abstract class NpcReferenceTables {
  /// Tabla 38 (TA por tipo): FIL, CON, PEN, CAL, ELE, FRI, ENE.
  static const armours = <String, List<int>>{
    'acolchada': [1, 1, 1, 1, 2, 2, 0],
    'cuero': [1, 0, 2, 1, 2, 1, 0],
    'cota de cuero': [1, 0, 2, 1, 2, 1, 0],
    'gabardina armada': [1, 0, 2, 1, 2, 2, 0],
    'gabardina': [1, 0, 2, 1, 2, 2, 0],
    'piel': [2, 1, 2, 1, 2, 2, 0],
    'completa de cuero': [1, 0, 2, 1, 2, 1, 0],
    'cuero endurecido': [2, 2, 2, 2, 2, 2, 0],
    'cuero tachonado': [3, 1, 2, 2, 1, 2, 0],
    'mallas': [4, 2, 1, 2, 0, 1, 0],
    'cota de mallas': [4, 2, 1, 2, 0, 1, 0],
    'peto': [4, 5, 4, 1, 0, 1, 0],
    'piezas': [4, 3, 2, 3, 2, 2, 0],
    'anillas': [4, 3, 1, 2, 0, 1, 0],
    'semicompleta': [4, 4, 4, 2, 0, 1, 1],
    'escamas': [4, 4, 4, 3, 0, 3, 1],
    'placas': [5, 4, 5, 3, 0, 3, 1],
    'completa pesada': [6, 6, 6, 4, 0, 4, 2],
    'de campana pesada': [7, 7, 7, 4, 0, 4, 2],
    'completa': [5, 5, 5, 4, 0, 4, 2],
  };

  /// Tabla de armas: crítico primario y secundario.
  static const weaponCriticals = <String, (String, String)>{
    'alabarda': ('FIL', 'CON'),
    'arpon': ('PEN', ''),
    'cadena': ('CON', ''),
    'cestus': ('PEN', 'FIL'),
    'cimitarra': ('FIL', ''),
    'daga de parada': ('PEN', 'FIL'),
    'daga': ('PEN', 'FIL'),
    'espada ancha': ('FIL', ''),
    'espada bastarda': ('FIL', 'CON'),
    'espada corta': ('PEN', 'FIL'),
    'espada larga': ('FIL', ''),
    'estilete': ('PEN', ''),
    'estoque': ('PEN', 'FIL'),
    'florete': ('PEN', ''),
    'garfio': ('PEN', ''),
    'garrote': ('CON', ''),
    'gran martillo de guerra': ('CON', ''),
    'guadana': ('FIL', 'CON'),
    'hacha de guerra': ('FIL', 'CON'),
    'hacha de mano': ('FIL', ''),
    'hacha de lenador': ('FIL', ''),
    'jabalina': ('PEN', ''),
    'lanza': ('PEN', ''),
    'latigo': ('FIL', 'CON'),
    'lazo': ('CON', ''),
    'mandoble': ('FIL', 'CON'),
    'mangual': ('CON', ''),
    'martillo de guerra': ('CON', ''),
    'mayal': ('CON', ''),
    'maza': ('CON', ''),
    'red de gladiador': ('CON', 'FIL'),
    'sable': ('FIL', 'PEN'),
    'tridente': ('PEN', ''),
    'vara': ('CON', ''),
    'nunchaku': ('CON', ''),
    'bumeran': ('CON', 'FIL'),
    'quebradora': ('CON', 'FIL'),
    'cuervo': ('CON', 'FIL'),
    'nodachi': ('FIL', ''),
    'tanto': ('FIL', ''),
    'tonfa': ('CON', ''),
    'abanico de combate': ('FIL', 'CON'),
    'sai': ('PEN', 'FIL'),
    'kusari-gama': ('FIL', 'CON'),
    'shuko': ('PEN', ''),
    'palo de madera': ('CON', ''),
    'barra metalica': ('CON', ''),
    'cuchillo de cocina': ('FIL', ''),
    'martillo': ('CON', ''),
    'azada': ('FIL', 'CON'),
    'hoz': ('FIL', 'PEN'),
    'pico': ('PEN', ''),
    'antorcha': ('CON', 'CAL'),
  };
}
